import plot3d
from Psatz_inner_bound_matlab import *
from plot import *

S_overl_veri = [torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [ True]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [ True]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [ True]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [False]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [ True]]), torch.Tensor([[ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [False],
                [False],
                [False],
                [False],
                [False],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [ True],
                [False],
                [ True],
                [ True],
                [False],
                [ True],
                [False],
                [ True]])]
M = []
S_overl = []
# S_overl_veri = []
S = []
B = []
limit = 100
model = ann.gen_nn()
model.load_state_dict(torch.load('obstacle_50_1_lr01.pt'), strict=True)

# Get layers' output
Layers = get_layers(model)
# Heuristic Search
H1w = Layers[1]  # Hidden layer pre-act = Layer 1
H1a = Layers[2]  # Hidden layer active = Layer 2
x_init = torch.Tensor([[0, -1.85, 0]])
x = find_one_zero_point_autograd(x_init, model)
S_overl = enumarate_intersections(x, H1w, H1a, model, M, S_overl, B, limit)
# plot3d.plot_act_3d(S_overl_veri)

# counter = 0
# for i in S_overl_veri:
#     W_overl, r_overl, B_act, B_inact = activated_weight_bias(model, i)
#     W_Bound = torch.Tensor(-B_act[0] + B_inact[0])
#     r_Bound = torch.Tensor(-B_act[1] - B_inact[1])
#     x1b = (prob.DOMAIN[0][0], prob.DOMAIN[0][1])
#     x2b = (prob.DOMAIN[1][0], prob.DOMAIN[1][1])
#     x3b = (prob.DOMAIN[2][0], prob.DOMAIN[2][1])
#     res_zero = linprog(c=[1, 1, 1],
#                        A_ub=W_Bound, b_ub=-r_Bound,
#                        A_eq=W_overl, b_eq=-r_overl, bounds=(x1b, x2b, x3b),
#                        method='simplex')
#     if res_zero.success:
#         counter += 1
# print('numb: ',len(S_overl_veri))
# print(counter)
plot3d.plot_act_3d(S_overl)